topics:
  [
    "/ackermann_cmd",
    "/brake",
    "/commands/motor/brake",
    "/commands/motor/current",
    "/commands/motor/duty_cycle",
    "/commands/motor/position",
    "/commands/motor/speed",
    "/commands/servo/position",
    "/drive",
    "/initialpose",
    "/joint_states",
    "/map",
    "/odom",
    "/odometry/filtered",
    "/parameter_events",
    "/pf/pose/odom",
    "/pf/viz/inferred_pose",
    "/pf/viz/particles",
    "/pf/viz/poly1",
    "/robot_description",
    "/scan",
    "/sensors/core",
    "/sensors/imu",
    "/sensors/imu/raw",
    "/sensors/servo_position_command",
    "/teleop",
    "/tf",
    "/tf_static",
    "/waypoints",
    "/telemetry/speed",
    "/telemetry/heading",
    "/telemetry/acceleration",
    "/telemetry/lap_time",
    "/telemetry/lateral_error",
    "/visualize/closest_waypoint_to_car",
    "/visualize/goal",
    "/visualize/waypoints",
    "/visualize/steering",
    "/visualize/turning_radius",
  ]
