  - RandomSamplingDataPointsFilter:
      prob: 0.8

  - AddDescriptorDataPointsFilter:
      descriptorName: probabilityDynamic 
      descriptorDimension: 1
      descriptorValues: [0.6]

  - SamplingSurfaceNormalDataPointsFilter:
      ratio: 0.5
      knn: 7
      samplingMethod: 0
      maxBoxDim: inf
      averageExistingDescriptors: 1
      keepNormals: 1
      keepDensities: 0
      keepEigenValues: 0
      keepEigenVectors: 0
